name: Atualizar PSI

on:
  schedule:
    - cron: "*/3 * * * *"  # A cada 3 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install requests

      - name: Executar scraper
        run: python scrape_psi.py

      - name: Commit e push com autenticação
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "miguelt007"
          git config --global user.email "miguelt007@gmail.com"
          git add data/psi.json
          git commit -m "Atualização automática" || echo "Nada para commitar"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/miguelt007/bolsa.git
          git push origin HEAD:main
